version: '2'


services:
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - '2181:2181'
  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_BROKER_ID=1
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_CREATE_TOPICS="test_topic:1:1"
      - KAFKA_REST_ZOOKEEPER_CONNECT=localhost:32181
      - KAFKA_REST_LISTENERS=http://localhost:8082
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8081 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock